### ISSUE TITLE
Request for the full dataset

### ISSUE THREAD

**Issue by vinybrasil** [pgbreen/NVM#1]
Hello, I would like to know if the full training dataset is available somewhere?

Thanks

**Comment by spzwart** [comment]
Dear Vinicyus,

you can find the code and data on github under:

https://github.com/pgbreen/NVM

good luck,
Simon


Prof. Simon Portegies Zwart
Leiden University
Sterrewacht Leiden
PO-Box 9513
2300 RA Leiden, the Netherlands
Tel: +31-(0)71 527 5737/8429

**Comment by vinybrasil** [comment]
Hi professor, thanks for replying.

Sorry for insisting, but in the repository there is only a part of the training dataset, since in the paper it says that the network was trained in 999 simulations and in the repository there are only 100 simulations. Is there any way for the teacher to give me the data from the other simulations? I am working with this data in my master's thesis.

Thanks again

**Comment by pgbreen** [comment]
Hello @vinybrasil 

Thank you for reaching out, as Simon mentioned there is code and sample data in the repo. Unfortunately, the file which contains all the runs is too large to upload to this repo. If you give me your email address I'll send you a link which you could use to download the data

**Comment by vinybrasil** [comment]
That would be awesome. My email is vinicyusbrasil1@hotmail.com

Thanks

**Comment by maxrdu** [comment]
Dear Phillip Green and Prof. Portegies Zwart, 
I would also be interested in obtaining the full dataset, would it be possible to upload the dataset to e.g. Zenodo or Figshare?
